# Generated by Django 5.0.1 on 2024-06-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_dailyrefreshcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshcounter',
            old_name='count',
            new_name='total_count',
        ),
    ]
